# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Mon Oct 22 17:40:13 2018
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setUpdatesEnabled(True)
        MainWindow.setVisible(True)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowIconText(_fromUtf8(""))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setWindowModified(False)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setAccessibleName(_fromUtf8(""))
        MainWindow.setAccessibleDescription(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setWindowFilePath(_fromUtf8(""))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setSizeGripEnabled(False)
        MainWindow.setModal(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setGeometry(QtCore.QRect(-20, -10, 821, 592))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.centralwidget.setPalette(palette)
        font = QtGui.QFont()
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setUpdatesEnabled(True)
        self.centralwidget.setVisible(True)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setWindowTitle(_fromUtf8(""))
        self.centralwidget.setWindowIconText(_fromUtf8(""))
        self.centralwidget.setWindowOpacity(1.0)
        self.centralwidget.setWindowModified(False)
        self.centralwidget.setToolTip(_fromUtf8(""))
        self.centralwidget.setStatusTip(_fromUtf8(""))
        self.centralwidget.setWhatsThis(_fromUtf8(""))
        self.centralwidget.setAccessibleName(_fromUtf8(""))
        self.centralwidget.setAccessibleDescription(_fromUtf8(""))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setWindowFilePath(_fromUtf8(""))
        self.centralwidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.RescanInputsPushButton = QtGui.QPushButton(self.centralwidget)
        self.RescanInputsPushButton.setEnabled(True)
        self.RescanInputsPushButton.setGeometry(QtCore.QRect(70, 50, 91, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RescanInputsPushButton.sizePolicy().hasHeightForWidth())
        self.RescanInputsPushButton.setSizePolicy(sizePolicy)
        self.RescanInputsPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.RescanInputsPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RescanInputsPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.RescanInputsPushButton.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.RescanInputsPushButton.setPalette(palette)
        font = QtGui.QFont()
        self.RescanInputsPushButton.setFont(font)
        self.RescanInputsPushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.RescanInputsPushButton.setMouseTracking(False)
        self.RescanInputsPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.RescanInputsPushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.RescanInputsPushButton.setUpdatesEnabled(True)
        self.RescanInputsPushButton.setVisible(True)
        self.RescanInputsPushButton.setAcceptDrops(False)
        self.RescanInputsPushButton.setWindowTitle(_fromUtf8(""))
        self.RescanInputsPushButton.setWindowIconText(_fromUtf8(""))
        self.RescanInputsPushButton.setWindowOpacity(1.0)
        self.RescanInputsPushButton.setWindowModified(False)
        self.RescanInputsPushButton.setToolTip(_fromUtf8(""))
        self.RescanInputsPushButton.setStatusTip(_fromUtf8(""))
        self.RescanInputsPushButton.setWhatsThis(_fromUtf8(""))
        self.RescanInputsPushButton.setAccessibleName(_fromUtf8(""))
        self.RescanInputsPushButton.setAccessibleDescription(_fromUtf8(""))
        self.RescanInputsPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RescanInputsPushButton.setAutoFillBackground(False)
        self.RescanInputsPushButton.setStyleSheet(_fromUtf8(""))
        self.RescanInputsPushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.RescanInputsPushButton.setWindowFilePath(_fromUtf8(""))
        self.RescanInputsPushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RescanInputsPushButton.setIconSize(QtCore.QSize(16, 16))
        self.RescanInputsPushButton.setShortcut(_fromUtf8(""))
        self.RescanInputsPushButton.setCheckable(False)
        self.RescanInputsPushButton.setChecked(False)
        self.RescanInputsPushButton.setAutoRepeat(False)
        self.RescanInputsPushButton.setAutoExclusive(False)
        self.RescanInputsPushButton.setAutoRepeatDelay(300)
        self.RescanInputsPushButton.setAutoRepeatInterval(100)
        self.RescanInputsPushButton.setDown(False)
        self.RescanInputsPushButton.setAutoDefault(True)
        self.RescanInputsPushButton.setDefault(True)
        self.RescanInputsPushButton.setFlat(False)
        self.RescanInputsPushButton.setObjectName(_fromUtf8("RescanInputsPushButton"))
        self.InputSelectionSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.InputSelectionSpinBox.setEnabled(True)
        self.InputSelectionSpinBox.setGeometry(QtCore.QRect(70, 110, 61, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSelectionSpinBox.sizePolicy().hasHeightForWidth())
        self.InputSelectionSpinBox.setSizePolicy(sizePolicy)
        self.InputSelectionSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.InputSelectionSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InputSelectionSpinBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.InputSelectionSpinBox.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.InputSelectionSpinBox.setPalette(palette)
        font = QtGui.QFont()
        self.InputSelectionSpinBox.setFont(font)
        self.InputSelectionSpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.InputSelectionSpinBox.setMouseTracking(False)
        self.InputSelectionSpinBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.InputSelectionSpinBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.InputSelectionSpinBox.setUpdatesEnabled(True)
        self.InputSelectionSpinBox.setVisible(True)
        self.InputSelectionSpinBox.setAcceptDrops(False)
        self.InputSelectionSpinBox.setWindowTitle(_fromUtf8(""))
        self.InputSelectionSpinBox.setWindowIconText(_fromUtf8(""))
        self.InputSelectionSpinBox.setWindowOpacity(1.0)
        self.InputSelectionSpinBox.setWindowModified(False)
        self.InputSelectionSpinBox.setToolTip(_fromUtf8(""))
        self.InputSelectionSpinBox.setStatusTip(_fromUtf8(""))
        self.InputSelectionSpinBox.setWhatsThis(_fromUtf8(""))
        self.InputSelectionSpinBox.setAccessibleName(_fromUtf8(""))
        self.InputSelectionSpinBox.setAccessibleDescription(_fromUtf8(""))
        self.InputSelectionSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InputSelectionSpinBox.setAutoFillBackground(False)
        self.InputSelectionSpinBox.setStyleSheet(_fromUtf8(""))
        self.InputSelectionSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.InputSelectionSpinBox.setWindowFilePath(_fromUtf8(""))
        self.InputSelectionSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.InputSelectionSpinBox.setWrapping(False)
        self.InputSelectionSpinBox.setFrame(True)
        self.InputSelectionSpinBox.setReadOnly(False)
        self.InputSelectionSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.InputSelectionSpinBox.setSpecialValueText(_fromUtf8(""))
        self.InputSelectionSpinBox.setAccelerated(False)
        self.InputSelectionSpinBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.InputSelectionSpinBox.setKeyboardTracking(True)
        self.InputSelectionSpinBox.setSuffix(_fromUtf8(""))
        self.InputSelectionSpinBox.setPrefix(_fromUtf8(""))
        self.InputSelectionSpinBox.setMinimum(0)
        self.InputSelectionSpinBox.setMaximum(99)
        self.InputSelectionSpinBox.setSingleStep(1)
        self.InputSelectionSpinBox.setProperty("value", 0)
        self.InputSelectionSpinBox.setObjectName(_fromUtf8("InputSelectionSpinBox"))
        self.qt_spinbox_lineedit = QtGui.QLineEdit(self.InputSelectionSpinBox)
        self.qt_spinbox_lineedit.setEnabled(True)
        self.qt_spinbox_lineedit.setGeometry(QtCore.QRect(1, 1, 43, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_spinbox_lineedit.sizePolicy().hasHeightForWidth())
        self.qt_spinbox_lineedit.setSizePolicy(sizePolicy)
        self.qt_spinbox_lineedit.setMinimumSize(QtCore.QSize(0, 0))
        self.qt_spinbox_lineedit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qt_spinbox_lineedit.setSizeIncrement(QtCore.QSize(0, 0))
        self.qt_spinbox_lineedit.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.qt_spinbox_lineedit.setPalette(palette)
        font = QtGui.QFont()
        self.qt_spinbox_lineedit.setFont(font)
        self.qt_spinbox_lineedit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.qt_spinbox_lineedit.setMouseTracking(True)
        self.qt_spinbox_lineedit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qt_spinbox_lineedit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.qt_spinbox_lineedit.setUpdatesEnabled(True)
        self.qt_spinbox_lineedit.setVisible(True)
        self.qt_spinbox_lineedit.setAcceptDrops(False)
        self.qt_spinbox_lineedit.setWindowTitle(_fromUtf8(""))
        self.qt_spinbox_lineedit.setWindowIconText(_fromUtf8(""))
        self.qt_spinbox_lineedit.setWindowOpacity(1.0)
        self.qt_spinbox_lineedit.setWindowModified(False)
        self.qt_spinbox_lineedit.setToolTip(_fromUtf8(""))
        self.qt_spinbox_lineedit.setStatusTip(_fromUtf8(""))
        self.qt_spinbox_lineedit.setWhatsThis(_fromUtf8(""))
        self.qt_spinbox_lineedit.setAccessibleName(_fromUtf8(""))
        self.qt_spinbox_lineedit.setAccessibleDescription(_fromUtf8(""))
        self.qt_spinbox_lineedit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qt_spinbox_lineedit.setAutoFillBackground(False)
        self.qt_spinbox_lineedit.setStyleSheet(_fromUtf8(""))
        self.qt_spinbox_lineedit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.qt_spinbox_lineedit.setWindowFilePath(_fromUtf8(""))
        self.qt_spinbox_lineedit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qt_spinbox_lineedit.setInputMask(_fromUtf8(""))
        self.qt_spinbox_lineedit.setMaxLength(32767)
        self.qt_spinbox_lineedit.setFrame(False)
        self.qt_spinbox_lineedit.setEchoMode(QtGui.QLineEdit.Normal)
        self.qt_spinbox_lineedit.setCursorPosition(1)
        self.qt_spinbox_lineedit.setModified(False)
        self.qt_spinbox_lineedit.setDragEnabled(False)
        self.qt_spinbox_lineedit.setReadOnly(False)
        self.qt_spinbox_lineedit.setPlaceholderText(_fromUtf8(""))
        self.qt_spinbox_lineedit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.qt_spinbox_lineedit.setObjectName(_fromUtf8("qt_spinbox_lineedit"))
        self.BirdNameLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.BirdNameLineEdit.setEnabled(True)
        self.BirdNameLineEdit.setGeometry(QtCore.QRect(60, 200, 111, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BirdNameLineEdit.sizePolicy().hasHeightForWidth())
        self.BirdNameLineEdit.setSizePolicy(sizePolicy)
        self.BirdNameLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.BirdNameLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BirdNameLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.BirdNameLineEdit.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.BirdNameLineEdit.setPalette(palette)
        font = QtGui.QFont()
        self.BirdNameLineEdit.setFont(font)
        self.BirdNameLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.BirdNameLineEdit.setMouseTracking(True)
        self.BirdNameLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.BirdNameLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BirdNameLineEdit.setUpdatesEnabled(True)
        self.BirdNameLineEdit.setVisible(True)
        self.BirdNameLineEdit.setAcceptDrops(True)
        self.BirdNameLineEdit.setWindowTitle(_fromUtf8(""))
        self.BirdNameLineEdit.setWindowIconText(_fromUtf8(""))
        self.BirdNameLineEdit.setWindowOpacity(1.0)
        self.BirdNameLineEdit.setWindowModified(False)
        self.BirdNameLineEdit.setToolTip(_fromUtf8(""))
        self.BirdNameLineEdit.setStatusTip(_fromUtf8(""))
        self.BirdNameLineEdit.setWhatsThis(_fromUtf8(""))
        self.BirdNameLineEdit.setAccessibleName(_fromUtf8(""))
        self.BirdNameLineEdit.setAccessibleDescription(_fromUtf8(""))
        self.BirdNameLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BirdNameLineEdit.setAutoFillBackground(False)
        self.BirdNameLineEdit.setStyleSheet(_fromUtf8(""))
        self.BirdNameLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.BirdNameLineEdit.setWindowFilePath(_fromUtf8(""))
        self.BirdNameLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.BirdNameLineEdit.setInputMask(_fromUtf8(""))
        self.BirdNameLineEdit.setMaxLength(32767)
        self.BirdNameLineEdit.setFrame(True)
        self.BirdNameLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.BirdNameLineEdit.setCursorPosition(6)
        self.BirdNameLineEdit.setModified(False)
        self.BirdNameLineEdit.setDragEnabled(False)
        self.BirdNameLineEdit.setReadOnly(False)
        self.BirdNameLineEdit.setPlaceholderText(_fromUtf8(""))
        self.BirdNameLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.BirdNameLineEdit.setObjectName(_fromUtf8("BirdNameLineEdit"))
        self.ThresholdLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ThresholdLineEdit.setEnabled(True)
        self.ThresholdLineEdit.setGeometry(QtCore.QRect(60, 250, 111, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThresholdLineEdit.sizePolicy().hasHeightForWidth())
        self.ThresholdLineEdit.setSizePolicy(sizePolicy)
        self.ThresholdLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.ThresholdLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ThresholdLineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.ThresholdLineEdit.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.ThresholdLineEdit.setPalette(palette)
        font = QtGui.QFont()
        self.ThresholdLineEdit.setFont(font)
        self.ThresholdLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ThresholdLineEdit.setMouseTracking(True)
        self.ThresholdLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ThresholdLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ThresholdLineEdit.setUpdatesEnabled(True)
        self.ThresholdLineEdit.setVisible(True)
        self.ThresholdLineEdit.setAcceptDrops(True)
        self.ThresholdLineEdit.setWindowTitle(_fromUtf8(""))
        self.ThresholdLineEdit.setWindowIconText(_fromUtf8(""))
        self.ThresholdLineEdit.setWindowOpacity(1.0)
        self.ThresholdLineEdit.setWindowModified(False)
        self.ThresholdLineEdit.setToolTip(_fromUtf8(""))
        self.ThresholdLineEdit.setStatusTip(_fromUtf8(""))
        self.ThresholdLineEdit.setWhatsThis(_fromUtf8(""))
        self.ThresholdLineEdit.setAccessibleName(_fromUtf8(""))
        self.ThresholdLineEdit.setAccessibleDescription(_fromUtf8(""))
        self.ThresholdLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThresholdLineEdit.setAutoFillBackground(False)
        self.ThresholdLineEdit.setStyleSheet(_fromUtf8(""))
        self.ThresholdLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ThresholdLineEdit.setWindowFilePath(_fromUtf8(""))
        self.ThresholdLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ThresholdLineEdit.setInputMask(_fromUtf8(""))
        self.ThresholdLineEdit.setMaxLength(32767)
        self.ThresholdLineEdit.setFrame(True)
        self.ThresholdLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.ThresholdLineEdit.setCursorPosition(3)
        self.ThresholdLineEdit.setModified(False)
        self.ThresholdLineEdit.setDragEnabled(False)
        self.ThresholdLineEdit.setReadOnly(False)
        self.ThresholdLineEdit.setPlaceholderText(_fromUtf8(""))
        self.ThresholdLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ThresholdLineEdit.setObjectName(_fromUtf8("ThresholdLineEdit"))
        self.BirdNameFixedTest = QtGui.QLabel(self.centralwidget)
        self.BirdNameFixedTest.setEnabled(True)
        self.BirdNameFixedTest.setGeometry(QtCore.QRect(40, 180, 71, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BirdNameFixedTest.sizePolicy().hasHeightForWidth())
        self.BirdNameFixedTest.setSizePolicy(sizePolicy)
        self.BirdNameFixedTest.setMinimumSize(QtCore.QSize(0, 0))
        self.BirdNameFixedTest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BirdNameFixedTest.setSizeIncrement(QtCore.QSize(0, 0))
        self.BirdNameFixedTest.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.BirdNameFixedTest.setPalette(palette)
        font = QtGui.QFont()
        self.BirdNameFixedTest.setFont(font)
        self.BirdNameFixedTest.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BirdNameFixedTest.setMouseTracking(False)
        self.BirdNameFixedTest.setFocusPolicy(QtCore.Qt.NoFocus)
        self.BirdNameFixedTest.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BirdNameFixedTest.setUpdatesEnabled(True)
        self.BirdNameFixedTest.setVisible(True)
        self.BirdNameFixedTest.setAcceptDrops(False)
        self.BirdNameFixedTest.setWindowTitle(_fromUtf8(""))
        self.BirdNameFixedTest.setWindowIconText(_fromUtf8(""))
        self.BirdNameFixedTest.setWindowOpacity(1.0)
        self.BirdNameFixedTest.setWindowModified(False)
        self.BirdNameFixedTest.setToolTip(_fromUtf8(""))
        self.BirdNameFixedTest.setStatusTip(_fromUtf8(""))
        self.BirdNameFixedTest.setWhatsThis(_fromUtf8(""))
        self.BirdNameFixedTest.setAccessibleName(_fromUtf8(""))
        self.BirdNameFixedTest.setAccessibleDescription(_fromUtf8(""))
        self.BirdNameFixedTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BirdNameFixedTest.setAutoFillBackground(False)
        self.BirdNameFixedTest.setStyleSheet(_fromUtf8(""))
        self.BirdNameFixedTest.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.BirdNameFixedTest.setWindowFilePath(_fromUtf8(""))
        self.BirdNameFixedTest.setInputMethodHints(QtCore.Qt.ImhNone)
        self.BirdNameFixedTest.setFrameShape(QtGui.QFrame.NoFrame)
        self.BirdNameFixedTest.setFrameShadow(QtGui.QFrame.Plain)
        self.BirdNameFixedTest.setLineWidth(1)
        self.BirdNameFixedTest.setMidLineWidth(0)
        self.BirdNameFixedTest.setFrameRect(QtCore.QRect(0, 0, 71, 16))
        self.BirdNameFixedTest.setTextFormat(QtCore.Qt.AutoText)
        self.BirdNameFixedTest.setScaledContents(False)
        self.BirdNameFixedTest.setWordWrap(False)
        self.BirdNameFixedTest.setMargin(0)
        self.BirdNameFixedTest.setIndent(-1)
        self.BirdNameFixedTest.setOpenExternalLinks(False)
        self.BirdNameFixedTest.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.BirdNameFixedTest.setObjectName(_fromUtf8("BirdNameFixedTest"))
        self.InputSelectionFixedText = QtGui.QLabel(self.centralwidget)
        self.InputSelectionFixedText.setEnabled(True)
        self.InputSelectionFixedText.setGeometry(QtCore.QRect(70, 90, 91, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSelectionFixedText.sizePolicy().hasHeightForWidth())
        self.InputSelectionFixedText.setSizePolicy(sizePolicy)
        self.InputSelectionFixedText.setMinimumSize(QtCore.QSize(0, 0))
        self.InputSelectionFixedText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InputSelectionFixedText.setSizeIncrement(QtCore.QSize(0, 0))
        self.InputSelectionFixedText.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.InputSelectionFixedText.setPalette(palette)
        font = QtGui.QFont()
        self.InputSelectionFixedText.setFont(font)
        self.InputSelectionFixedText.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.InputSelectionFixedText.setMouseTracking(False)
        self.InputSelectionFixedText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.InputSelectionFixedText.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.InputSelectionFixedText.setUpdatesEnabled(True)
        self.InputSelectionFixedText.setVisible(True)
        self.InputSelectionFixedText.setAcceptDrops(False)
        self.InputSelectionFixedText.setWindowTitle(_fromUtf8(""))
        self.InputSelectionFixedText.setWindowIconText(_fromUtf8(""))
        self.InputSelectionFixedText.setWindowOpacity(1.0)
        self.InputSelectionFixedText.setWindowModified(False)
        self.InputSelectionFixedText.setToolTip(_fromUtf8(""))
        self.InputSelectionFixedText.setStatusTip(_fromUtf8(""))
        self.InputSelectionFixedText.setWhatsThis(_fromUtf8(""))
        self.InputSelectionFixedText.setAccessibleName(_fromUtf8(""))
        self.InputSelectionFixedText.setAccessibleDescription(_fromUtf8(""))
        self.InputSelectionFixedText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InputSelectionFixedText.setAutoFillBackground(False)
        self.InputSelectionFixedText.setStyleSheet(_fromUtf8(""))
        self.InputSelectionFixedText.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.InputSelectionFixedText.setWindowFilePath(_fromUtf8(""))
        self.InputSelectionFixedText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InputSelectionFixedText.setFrameShape(QtGui.QFrame.NoFrame)
        self.InputSelectionFixedText.setFrameShadow(QtGui.QFrame.Plain)
        self.InputSelectionFixedText.setLineWidth(1)
        self.InputSelectionFixedText.setMidLineWidth(0)
        self.InputSelectionFixedText.setFrameRect(QtCore.QRect(0, 0, 91, 16))
        self.InputSelectionFixedText.setTextFormat(QtCore.Qt.AutoText)
        self.InputSelectionFixedText.setScaledContents(False)
        self.InputSelectionFixedText.setWordWrap(False)
        self.InputSelectionFixedText.setMargin(0)
        self.InputSelectionFixedText.setIndent(-1)
        self.InputSelectionFixedText.setOpenExternalLinks(False)
        self.InputSelectionFixedText.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.InputSelectionFixedText.setObjectName(_fromUtf8("InputSelectionFixedText"))
        self.ThresholdFixedText = QtGui.QLabel(self.centralwidget)
        self.ThresholdFixedText.setEnabled(True)
        self.ThresholdFixedText.setGeometry(QtCore.QRect(40, 230, 71, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThresholdFixedText.sizePolicy().hasHeightForWidth())
        self.ThresholdFixedText.setSizePolicy(sizePolicy)
        self.ThresholdFixedText.setMinimumSize(QtCore.QSize(0, 0))
        self.ThresholdFixedText.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ThresholdFixedText.setSizeIncrement(QtCore.QSize(0, 0))
        self.ThresholdFixedText.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.ThresholdFixedText.setPalette(palette)
        font = QtGui.QFont()
        self.ThresholdFixedText.setFont(font)
        self.ThresholdFixedText.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ThresholdFixedText.setMouseTracking(False)
        self.ThresholdFixedText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ThresholdFixedText.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ThresholdFixedText.setUpdatesEnabled(True)
        self.ThresholdFixedText.setVisible(True)
        self.ThresholdFixedText.setAcceptDrops(False)
        self.ThresholdFixedText.setWindowTitle(_fromUtf8(""))
        self.ThresholdFixedText.setWindowIconText(_fromUtf8(""))
        self.ThresholdFixedText.setWindowOpacity(1.0)
        self.ThresholdFixedText.setWindowModified(False)
        self.ThresholdFixedText.setToolTip(_fromUtf8(""))
        self.ThresholdFixedText.setStatusTip(_fromUtf8(""))
        self.ThresholdFixedText.setWhatsThis(_fromUtf8(""))
        self.ThresholdFixedText.setAccessibleName(_fromUtf8(""))
        self.ThresholdFixedText.setAccessibleDescription(_fromUtf8(""))
        self.ThresholdFixedText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThresholdFixedText.setAutoFillBackground(False)
        self.ThresholdFixedText.setStyleSheet(_fromUtf8(""))
        self.ThresholdFixedText.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ThresholdFixedText.setWindowFilePath(_fromUtf8(""))
        self.ThresholdFixedText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ThresholdFixedText.setFrameShape(QtGui.QFrame.NoFrame)
        self.ThresholdFixedText.setFrameShadow(QtGui.QFrame.Plain)
        self.ThresholdFixedText.setLineWidth(1)
        self.ThresholdFixedText.setMidLineWidth(0)
        self.ThresholdFixedText.setFrameRect(QtCore.QRect(0, 0, 71, 16))
        self.ThresholdFixedText.setTextFormat(QtCore.Qt.AutoText)
        self.ThresholdFixedText.setScaledContents(False)
        self.ThresholdFixedText.setWordWrap(False)
        self.ThresholdFixedText.setMargin(0)
        self.ThresholdFixedText.setIndent(-1)
        self.ThresholdFixedText.setOpenExternalLinks(False)
        self.ThresholdFixedText.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.ThresholdFixedText.setObjectName(_fromUtf8("ThresholdFixedText"))
        self.StopPushButton = QtGui.QPushButton(self.centralwidget)
        self.StopPushButton.setEnabled(True)
        self.StopPushButton.setGeometry(QtCore.QRect(680, 470, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopPushButton.sizePolicy().hasHeightForWidth())
        self.StopPushButton.setSizePolicy(sizePolicy)
        self.StopPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StopPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StopPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.StopPushButton.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.StopPushButton.setPalette(palette)
        font = QtGui.QFont()
        self.StopPushButton.setFont(font)
        self.StopPushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.StopPushButton.setMouseTracking(False)
        self.StopPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.StopPushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.StopPushButton.setUpdatesEnabled(True)
        self.StopPushButton.setVisible(True)
        self.StopPushButton.setAcceptDrops(False)
        self.StopPushButton.setWindowTitle(_fromUtf8(""))
        self.StopPushButton.setWindowIconText(_fromUtf8(""))
        self.StopPushButton.setWindowOpacity(1.0)
        self.StopPushButton.setWindowModified(False)
        self.StopPushButton.setToolTip(_fromUtf8(""))
        self.StopPushButton.setStatusTip(_fromUtf8(""))
        self.StopPushButton.setWhatsThis(_fromUtf8(""))
        self.StopPushButton.setAccessibleName(_fromUtf8(""))
        self.StopPushButton.setAccessibleDescription(_fromUtf8(""))
        self.StopPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StopPushButton.setAutoFillBackground(False)
        self.StopPushButton.setStyleSheet(_fromUtf8(""))
        self.StopPushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.StopPushButton.setWindowFilePath(_fromUtf8(""))
        self.StopPushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.StopPushButton.setIconSize(QtCore.QSize(16, 16))
        self.StopPushButton.setShortcut(_fromUtf8(""))
        self.StopPushButton.setCheckable(False)
        self.StopPushButton.setChecked(False)
        self.StopPushButton.setAutoRepeat(False)
        self.StopPushButton.setAutoExclusive(False)
        self.StopPushButton.setAutoRepeatDelay(300)
        self.StopPushButton.setAutoRepeatInterval(100)
        self.StopPushButton.setDown(False)
        self.StopPushButton.setAutoDefault(True)
        self.StopPushButton.setDefault(False)
        self.StopPushButton.setFlat(False)
        self.StopPushButton.setObjectName(_fromUtf8("StopPushButton"))
        self.StartPushButton = QtGui.QPushButton(self.centralwidget)
        self.StartPushButton.setEnabled(True)
        self.StartPushButton.setGeometry(QtCore.QRect(560, 470, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartPushButton.sizePolicy().hasHeightForWidth())
        self.StartPushButton.setSizePolicy(sizePolicy)
        self.StartPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StartPushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StartPushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.StartPushButton.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.StartPushButton.setPalette(palette)
        font = QtGui.QFont()
        self.StartPushButton.setFont(font)
        self.StartPushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.StartPushButton.setMouseTracking(False)
        self.StartPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.StartPushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.StartPushButton.setUpdatesEnabled(True)
        self.StartPushButton.setVisible(True)
        self.StartPushButton.setAcceptDrops(False)
        self.StartPushButton.setWindowTitle(_fromUtf8(""))
        self.StartPushButton.setWindowIconText(_fromUtf8(""))
        self.StartPushButton.setWindowOpacity(1.0)
        self.StartPushButton.setWindowModified(False)
        self.StartPushButton.setToolTip(_fromUtf8(""))
        self.StartPushButton.setStatusTip(_fromUtf8(""))
        self.StartPushButton.setWhatsThis(_fromUtf8(""))
        self.StartPushButton.setAccessibleName(_fromUtf8(""))
        self.StartPushButton.setAccessibleDescription(_fromUtf8(""))
        self.StartPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartPushButton.setAutoFillBackground(False)
        self.StartPushButton.setStyleSheet(_fromUtf8(""))
        self.StartPushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.StartPushButton.setWindowFilePath(_fromUtf8(""))
        self.StartPushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.StartPushButton.setIconSize(QtCore.QSize(16, 16))
        self.StartPushButton.setShortcut(_fromUtf8(""))
        self.StartPushButton.setCheckable(False)
        self.StartPushButton.setChecked(False)
        self.StartPushButton.setAutoRepeat(False)
        self.StartPushButton.setAutoExclusive(False)
        self.StartPushButton.setAutoRepeatDelay(300)
        self.StartPushButton.setAutoRepeatInterval(100)
        self.StartPushButton.setDown(False)
        self.StartPushButton.setAutoDefault(True)
        self.StartPushButton.setDefault(False)
        self.StartPushButton.setFlat(False)
        self.StartPushButton.setObjectName(_fromUtf8("StartPushButton"))
        self.ListeningTextBox = QtGui.QLabel(self.centralwidget)
        self.ListeningTextBox.setEnabled(True)
        self.ListeningTextBox.setGeometry(QtCore.QRect(590, 380, 161, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListeningTextBox.sizePolicy().hasHeightForWidth())
        self.ListeningTextBox.setSizePolicy(sizePolicy)
        self.ListeningTextBox.setMinimumSize(QtCore.QSize(0, 0))
        self.ListeningTextBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ListeningTextBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.ListeningTextBox.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.ListeningTextBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.ListeningTextBox.setFont(font)
        self.ListeningTextBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ListeningTextBox.setMouseTracking(False)
        self.ListeningTextBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ListeningTextBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ListeningTextBox.setUpdatesEnabled(True)
        self.ListeningTextBox.setVisible(True)
        self.ListeningTextBox.setAcceptDrops(False)
        self.ListeningTextBox.setWindowTitle(_fromUtf8(""))
        self.ListeningTextBox.setWindowIconText(_fromUtf8(""))
        self.ListeningTextBox.setWindowOpacity(1.0)
        self.ListeningTextBox.setWindowModified(False)
        self.ListeningTextBox.setToolTip(_fromUtf8(""))
        self.ListeningTextBox.setStatusTip(_fromUtf8(""))
        self.ListeningTextBox.setWhatsThis(_fromUtf8(""))
        self.ListeningTextBox.setAccessibleName(_fromUtf8(""))
        self.ListeningTextBox.setAccessibleDescription(_fromUtf8(""))
        self.ListeningTextBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ListeningTextBox.setAutoFillBackground(False)
        self.ListeningTextBox.setStyleSheet(_fromUtf8(""))
        self.ListeningTextBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ListeningTextBox.setWindowFilePath(_fromUtf8(""))
        self.ListeningTextBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ListeningTextBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.ListeningTextBox.setFrameShadow(QtGui.QFrame.Plain)
        self.ListeningTextBox.setLineWidth(1)
        self.ListeningTextBox.setMidLineWidth(0)
        self.ListeningTextBox.setFrameRect(QtCore.QRect(0, 0, 161, 41))
        self.ListeningTextBox.setText(_fromUtf8(""))
        self.ListeningTextBox.setTextFormat(QtCore.Qt.AutoText)
        self.ListeningTextBox.setScaledContents(False)
        self.ListeningTextBox.setWordWrap(False)
        self.ListeningTextBox.setMargin(0)
        self.ListeningTextBox.setIndent(-1)
        self.ListeningTextBox.setOpenExternalLinks(False)
        self.ListeningTextBox.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.ListeningTextBox.setObjectName(_fromUtf8("ListeningTextBox"))
        self.WorkingDirpushButton = QtGui.QPushButton(self.centralwidget)
        self.WorkingDirpushButton.setEnabled(True)
        self.WorkingDirpushButton.setGeometry(QtCore.QRect(220, 200, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WorkingDirpushButton.sizePolicy().hasHeightForWidth())
        self.WorkingDirpushButton.setSizePolicy(sizePolicy)
        self.WorkingDirpushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.WorkingDirpushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.WorkingDirpushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.WorkingDirpushButton.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.WorkingDirpushButton.setPalette(palette)
        font = QtGui.QFont()
        self.WorkingDirpushButton.setFont(font)
        self.WorkingDirpushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.WorkingDirpushButton.setMouseTracking(False)
        self.WorkingDirpushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.WorkingDirpushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.WorkingDirpushButton.setUpdatesEnabled(True)
        self.WorkingDirpushButton.setVisible(True)
        self.WorkingDirpushButton.setAcceptDrops(False)
        self.WorkingDirpushButton.setWindowTitle(_fromUtf8(""))
        self.WorkingDirpushButton.setWindowIconText(_fromUtf8(""))
        self.WorkingDirpushButton.setWindowOpacity(1.0)
        self.WorkingDirpushButton.setWindowModified(False)
        self.WorkingDirpushButton.setToolTip(_fromUtf8(""))
        self.WorkingDirpushButton.setStatusTip(_fromUtf8(""))
        self.WorkingDirpushButton.setWhatsThis(_fromUtf8(""))
        self.WorkingDirpushButton.setAccessibleName(_fromUtf8(""))
        self.WorkingDirpushButton.setAccessibleDescription(_fromUtf8(""))
        self.WorkingDirpushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WorkingDirpushButton.setAutoFillBackground(False)
        self.WorkingDirpushButton.setStyleSheet(_fromUtf8(""))
        self.WorkingDirpushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.WorkingDirpushButton.setWindowFilePath(_fromUtf8(""))
        self.WorkingDirpushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.WorkingDirpushButton.setIconSize(QtCore.QSize(16, 16))
        self.WorkingDirpushButton.setShortcut(_fromUtf8(""))
        self.WorkingDirpushButton.setCheckable(False)
        self.WorkingDirpushButton.setChecked(False)
        self.WorkingDirpushButton.setAutoRepeat(False)
        self.WorkingDirpushButton.setAutoExclusive(False)
        self.WorkingDirpushButton.setAutoRepeatDelay(300)
        self.WorkingDirpushButton.setAutoRepeatInterval(100)
        self.WorkingDirpushButton.setDown(False)
        self.WorkingDirpushButton.setAutoDefault(True)
        self.WorkingDirpushButton.setDefault(False)
        self.WorkingDirpushButton.setFlat(False)
        self.WorkingDirpushButton.setObjectName(_fromUtf8("WorkingDirpushButton"))
        self.BufferTimeSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.BufferTimeSpinBox.setEnabled(True)
        self.BufferTimeSpinBox.setGeometry(QtCore.QRect(60, 300, 61, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BufferTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.BufferTimeSpinBox.setSizePolicy(sizePolicy)
        self.BufferTimeSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.BufferTimeSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BufferTimeSpinBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.BufferTimeSpinBox.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.BufferTimeSpinBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.BufferTimeSpinBox.setFont(font)
        self.BufferTimeSpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BufferTimeSpinBox.setMouseTracking(False)
        self.BufferTimeSpinBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.BufferTimeSpinBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BufferTimeSpinBox.setUpdatesEnabled(True)
        self.BufferTimeSpinBox.setVisible(True)
        self.BufferTimeSpinBox.setAcceptDrops(False)
        self.BufferTimeSpinBox.setWindowTitle(_fromUtf8(""))
        self.BufferTimeSpinBox.setWindowIconText(_fromUtf8(""))
        self.BufferTimeSpinBox.setWindowOpacity(1.0)
        self.BufferTimeSpinBox.setWindowModified(False)
        self.BufferTimeSpinBox.setToolTip(_fromUtf8(""))
        self.BufferTimeSpinBox.setStatusTip(_fromUtf8(""))
        self.BufferTimeSpinBox.setWhatsThis(_fromUtf8(""))
        self.BufferTimeSpinBox.setAccessibleName(_fromUtf8(""))
        self.BufferTimeSpinBox.setAccessibleDescription(_fromUtf8(""))
        self.BufferTimeSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BufferTimeSpinBox.setAutoFillBackground(False)
        self.BufferTimeSpinBox.setStyleSheet(_fromUtf8(""))
        self.BufferTimeSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.BufferTimeSpinBox.setWindowFilePath(_fromUtf8(""))
        self.BufferTimeSpinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.BufferTimeSpinBox.setWrapping(False)
        self.BufferTimeSpinBox.setFrame(True)
        self.BufferTimeSpinBox.setReadOnly(False)
        self.BufferTimeSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.BufferTimeSpinBox.setSpecialValueText(_fromUtf8(""))
        self.BufferTimeSpinBox.setAccelerated(False)
        self.BufferTimeSpinBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToPreviousValue)
        self.BufferTimeSpinBox.setKeyboardTracking(True)
        self.BufferTimeSpinBox.setSuffix(_fromUtf8(""))
        self.BufferTimeSpinBox.setPrefix(_fromUtf8(""))
        self.BufferTimeSpinBox.setMinimum(1)
        self.BufferTimeSpinBox.setMaximum(99)
        self.BufferTimeSpinBox.setSingleStep(1)
        self.BufferTimeSpinBox.setProperty("value", 1)
        self.BufferTimeSpinBox.setObjectName(_fromUtf8("BufferTimeSpinBox"))
        self.qt_spinbox_lineedit1 = QtGui.QLineEdit(self.BufferTimeSpinBox)
        self.qt_spinbox_lineedit1.setEnabled(True)
        self.qt_spinbox_lineedit1.setGeometry(QtCore.QRect(1, 1, 43, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_spinbox_lineedit1.sizePolicy().hasHeightForWidth())
        self.qt_spinbox_lineedit1.setSizePolicy(sizePolicy)
        self.qt_spinbox_lineedit1.setMinimumSize(QtCore.QSize(0, 0))
        self.qt_spinbox_lineedit1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qt_spinbox_lineedit1.setSizeIncrement(QtCore.QSize(0, 0))
        self.qt_spinbox_lineedit1.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.qt_spinbox_lineedit1.setPalette(palette)
        font = QtGui.QFont()
        self.qt_spinbox_lineedit1.setFont(font)
        self.qt_spinbox_lineedit1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.qt_spinbox_lineedit1.setMouseTracking(True)
        self.qt_spinbox_lineedit1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qt_spinbox_lineedit1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.qt_spinbox_lineedit1.setUpdatesEnabled(True)
        self.qt_spinbox_lineedit1.setVisible(True)
        self.qt_spinbox_lineedit1.setAcceptDrops(False)
        self.qt_spinbox_lineedit1.setWindowTitle(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setWindowIconText(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setWindowOpacity(1.0)
        self.qt_spinbox_lineedit1.setWindowModified(False)
        self.qt_spinbox_lineedit1.setToolTip(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setStatusTip(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setWhatsThis(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setAccessibleName(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setAccessibleDescription(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qt_spinbox_lineedit1.setAutoFillBackground(False)
        self.qt_spinbox_lineedit1.setStyleSheet(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.qt_spinbox_lineedit1.setWindowFilePath(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qt_spinbox_lineedit1.setInputMask(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setMaxLength(32767)
        self.qt_spinbox_lineedit1.setFrame(False)
        self.qt_spinbox_lineedit1.setEchoMode(QtGui.QLineEdit.Normal)
        self.qt_spinbox_lineedit1.setCursorPosition(1)
        self.qt_spinbox_lineedit1.setModified(False)
        self.qt_spinbox_lineedit1.setDragEnabled(False)
        self.qt_spinbox_lineedit1.setReadOnly(False)
        self.qt_spinbox_lineedit1.setPlaceholderText(_fromUtf8(""))
        self.qt_spinbox_lineedit1.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.qt_spinbox_lineedit1.setObjectName(_fromUtf8("qt_spinbox_lineedit1"))
        self.ThresholdFixedText_2 = QtGui.QLabel(self.centralwidget)
        self.ThresholdFixedText_2.setEnabled(True)
        self.ThresholdFixedText_2.setGeometry(QtCore.QRect(40, 280, 71, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThresholdFixedText_2.sizePolicy().hasHeightForWidth())
        self.ThresholdFixedText_2.setSizePolicy(sizePolicy)
        self.ThresholdFixedText_2.setMinimumSize(QtCore.QSize(0, 0))
        self.ThresholdFixedText_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ThresholdFixedText_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.ThresholdFixedText_2.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.ThresholdFixedText_2.setPalette(palette)
        font = QtGui.QFont()
        self.ThresholdFixedText_2.setFont(font)
        self.ThresholdFixedText_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ThresholdFixedText_2.setMouseTracking(False)
        self.ThresholdFixedText_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ThresholdFixedText_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ThresholdFixedText_2.setUpdatesEnabled(True)
        self.ThresholdFixedText_2.setVisible(True)
        self.ThresholdFixedText_2.setAcceptDrops(False)
        self.ThresholdFixedText_2.setWindowTitle(_fromUtf8(""))
        self.ThresholdFixedText_2.setWindowIconText(_fromUtf8(""))
        self.ThresholdFixedText_2.setWindowOpacity(1.0)
        self.ThresholdFixedText_2.setWindowModified(False)
        self.ThresholdFixedText_2.setToolTip(_fromUtf8(""))
        self.ThresholdFixedText_2.setStatusTip(_fromUtf8(""))
        self.ThresholdFixedText_2.setWhatsThis(_fromUtf8(""))
        self.ThresholdFixedText_2.setAccessibleName(_fromUtf8(""))
        self.ThresholdFixedText_2.setAccessibleDescription(_fromUtf8(""))
        self.ThresholdFixedText_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThresholdFixedText_2.setAutoFillBackground(False)
        self.ThresholdFixedText_2.setStyleSheet(_fromUtf8(""))
        self.ThresholdFixedText_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ThresholdFixedText_2.setWindowFilePath(_fromUtf8(""))
        self.ThresholdFixedText_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ThresholdFixedText_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.ThresholdFixedText_2.setFrameShadow(QtGui.QFrame.Plain)
        self.ThresholdFixedText_2.setLineWidth(1)
        self.ThresholdFixedText_2.setMidLineWidth(0)
        self.ThresholdFixedText_2.setFrameRect(QtCore.QRect(0, 0, 71, 16))
        self.ThresholdFixedText_2.setTextFormat(QtCore.Qt.AutoText)
        self.ThresholdFixedText_2.setScaledContents(False)
        self.ThresholdFixedText_2.setWordWrap(False)
        self.ThresholdFixedText_2.setMargin(0)
        self.ThresholdFixedText_2.setIndent(-1)
        self.ThresholdFixedText_2.setOpenExternalLinks(False)
        self.ThresholdFixedText_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.ThresholdFixedText_2.setObjectName(_fromUtf8("ThresholdFixedText_2"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(450, 150, 121, 17))
        self.radioButton.setChecked(False)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(480, 190, 82, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(480, 210, 82, 17))
        self.radioButton_3.setVisible(True)
        self.radioButton_2.setVisible(True)
        self.radioButton.setVisible(True)
        
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.GraphWidget = PlotWidget(self.centralwidget)
        self.GraphWidget.setGeometry(QtCore.QRect(80, 350, 401, 201))
        self.GraphWidget.setObjectName(_fromUtf8("GraphWidget"))
        self.GraphWidget.setVisible(True);
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMinimumSize(QtCore.QSize(0, 0))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menubar.setSizeIncrement(QtCore.QSize(0, 0))
        self.menubar.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.menubar.setPalette(palette)
        font = QtGui.QFont()
        self.menubar.setFont(font)
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setMouseTracking(True)
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setUpdatesEnabled(True)
        self.menubar.setVisible(True)
        self.menubar.setAcceptDrops(False)
        self.menubar.setWindowTitle(_fromUtf8(""))
        self.menubar.setWindowIconText(_fromUtf8(""))
        self.menubar.setWindowOpacity(1.0)
        self.menubar.setWindowModified(False)
        self.menubar.setToolTip(_fromUtf8(""))
        self.menubar.setStatusTip(_fromUtf8(""))
        self.menubar.setWhatsThis(_fromUtf8(""))
        self.menubar.setAccessibleName(_fromUtf8(""))
        self.menubar.setAccessibleDescription(_fromUtf8(""))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menubar.setWindowFilePath(_fromUtf8(""))
        self.menubar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.qt_menubar_ext_button = QtGui.QToolButton(self.menubar)
        self.qt_menubar_ext_button.setEnabled(True)
        self.qt_menubar_ext_button.setGeometry(QtCore.QRect(0, 0, 100, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_menubar_ext_button.sizePolicy().hasHeightForWidth())
        self.qt_menubar_ext_button.setSizePolicy(sizePolicy)
        self.qt_menubar_ext_button.setMinimumSize(QtCore.QSize(0, 0))
        self.qt_menubar_ext_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qt_menubar_ext_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.qt_menubar_ext_button.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.qt_menubar_ext_button.setPalette(palette)
        font = QtGui.QFont()
        self.qt_menubar_ext_button.setFont(font)
        self.qt_menubar_ext_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.qt_menubar_ext_button.setMouseTracking(False)
        self.qt_menubar_ext_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qt_menubar_ext_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.qt_menubar_ext_button.setUpdatesEnabled(True)
        self.qt_menubar_ext_button.setVisible(False)
        self.qt_menubar_ext_button.setAcceptDrops(False)
        self.qt_menubar_ext_button.setWindowTitle(_fromUtf8(""))
        self.qt_menubar_ext_button.setWindowIconText(_fromUtf8(""))
        self.qt_menubar_ext_button.setWindowOpacity(1.0)
        self.qt_menubar_ext_button.setWindowModified(False)
        self.qt_menubar_ext_button.setToolTip(_fromUtf8(""))
        self.qt_menubar_ext_button.setStatusTip(_fromUtf8(""))
        self.qt_menubar_ext_button.setWhatsThis(_fromUtf8(""))
        self.qt_menubar_ext_button.setAccessibleName(_fromUtf8(""))
        self.qt_menubar_ext_button.setAccessibleDescription(_fromUtf8(""))
        self.qt_menubar_ext_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qt_menubar_ext_button.setAutoFillBackground(False)
        self.qt_menubar_ext_button.setStyleSheet(_fromUtf8(""))
        self.qt_menubar_ext_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.qt_menubar_ext_button.setWindowFilePath(_fromUtf8(""))
        self.qt_menubar_ext_button.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qt_menubar_ext_button.setText(_fromUtf8(""))
        self.qt_menubar_ext_button.setIconSize(QtCore.QSize(16, 16))
        self.qt_menubar_ext_button.setShortcut(_fromUtf8(""))
        self.qt_menubar_ext_button.setCheckable(False)
        self.qt_menubar_ext_button.setChecked(False)
        self.qt_menubar_ext_button.setAutoRepeat(False)
        self.qt_menubar_ext_button.setAutoExclusive(False)
        self.qt_menubar_ext_button.setAutoRepeatDelay(300)
        self.qt_menubar_ext_button.setAutoRepeatInterval(100)
        self.qt_menubar_ext_button.setDown(False)
        self.qt_menubar_ext_button.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.qt_menubar_ext_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.qt_menubar_ext_button.setAutoRaise(True)
        self.qt_menubar_ext_button.setArrowType(QtCore.Qt.NoArrow)
        self.qt_menubar_ext_button.setObjectName(_fromUtf8("qt_menubar_ext_button"))
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setGeometry(QtCore.QRect(0, 0, 3, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 0))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statusbar.setSizeIncrement(QtCore.QSize(0, 0))
        self.statusbar.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.statusbar.setPalette(palette)
        font = QtGui.QFont()
        self.statusbar.setFont(font)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setMouseTracking(False)
        self.statusbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.statusbar.setUpdatesEnabled(True)
        self.statusbar.setVisible(True)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setWindowTitle(_fromUtf8(""))
        self.statusbar.setWindowIconText(_fromUtf8(""))
        self.statusbar.setWindowOpacity(1.0)
        self.statusbar.setWindowModified(False)
        self.statusbar.setToolTip(_fromUtf8(""))
        self.statusbar.setStatusTip(_fromUtf8(""))
        self.statusbar.setWhatsThis(_fromUtf8(""))
        self.statusbar.setAccessibleName(_fromUtf8(""))
        self.statusbar.setAccessibleDescription(_fromUtf8(""))
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setStyleSheet(_fromUtf8(""))
        self.statusbar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.statusbar.setWindowFilePath(_fromUtf8(""))
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        self.sizeGrip = QSizeGrip(self.statusbar)
        self.sizeGrip.setEnabled(True)
        self.sizeGrip.setGeometry(QtCore.QRect(11, 18, 0, 0))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeGrip.sizePolicy().hasHeightForWidth())
        self.sizeGrip.setSizePolicy(sizePolicy)
        self.sizeGrip.setMinimumSize(QtCore.QSize(0, 0))
        self.sizeGrip.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sizeGrip.setSizeIncrement(QtCore.QSize(0, 0))
        self.sizeGrip.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        self.sizeGrip.setPalette(palette)
        font = QtGui.QFont()
        self.sizeGrip.setFont(font)
        self.sizeGrip.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.sizeGrip.setMouseTracking(False)
        self.sizeGrip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sizeGrip.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.sizeGrip.setUpdatesEnabled(True)
        self.sizeGrip.setVisible(True)
        self.sizeGrip.setAcceptDrops(False)
        self.sizeGrip.setWindowTitle(_fromUtf8(""))
        self.sizeGrip.setWindowIconText(_fromUtf8(""))
        self.sizeGrip.setWindowOpacity(1.0)
        self.sizeGrip.setWindowModified(False)
        self.sizeGrip.setToolTip(_fromUtf8(""))
        self.sizeGrip.setStatusTip(_fromUtf8(""))
        self.sizeGrip.setWhatsThis(_fromUtf8(""))
        self.sizeGrip.setAccessibleName(_fromUtf8(""))
        self.sizeGrip.setAccessibleDescription(_fromUtf8(""))
        self.sizeGrip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sizeGrip.setAutoFillBackground(False)
        self.sizeGrip.setStyleSheet(_fromUtf8(""))
        self.sizeGrip.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sizeGrip.setWindowFilePath(_fromUtf8(""))
        self.sizeGrip.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sizeGrip.setObjectName(_fromUtf8("sizeGrip"))
        self.layoutWidget = QtGui.QWidget(self.statusbar)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        spacerItem = QtGui.QSpacerItem(0, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem1 = QtGui.QSpacerItem(2, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hboxlayout.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(0, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.hboxlayout.addItem(spacerItem3)
        self.vboxlayout.addLayout(self.hboxlayout)
        spacerItem4 = QtGui.QSpacerItem(0, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem4)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.RescanInputsPushButton.setText(_translate("MainWindow", "Rescan Inputs", None))
        self.qt_spinbox_lineedit.setText(_translate("MainWindow", "0", None))
        self.BirdNameLineEdit.setText(_translate("MainWindow", "output", None))
        self.ThresholdLineEdit.setText(_translate("MainWindow", "100", None))
        self.BirdNameFixedTest.setText(_translate("MainWindow", "Bird Name?", None))
        self.InputSelectionFixedText.setText(_translate("MainWindow", "Input Selection", None))
        self.ThresholdFixedText.setText(_translate("MainWindow", "Threshold", None))
        self.StopPushButton.setText(_translate("MainWindow", "Stop", None))
        self.StartPushButton.setText(_translate("MainWindow", "Start", None))
        self.WorkingDirpushButton.setText(_translate("MainWindow", "Working Dir", None))
        self.qt_spinbox_lineedit1.setText(_translate("MainWindow", "1", None))
        self.ThresholdFixedText_2.setText(_translate("MainWindow", "Buffer time (s)", None))
        self.radioButton.setText(_translate("MainWindow", "Stereo Recording", None))
        self.radioButton_2.setText(_translate("MainWindow", "Trigger Left", None))
        self.radioButton_3.setText(_translate("MainWindow", "Trigger Right", None))

from pyqtgraph import PlotWidget
from PyQt4.QtGui import QSizeGrip
